services:
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - ./src:/app
    ports:
      - 8000:8000

  test:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    command: pytest
